### ISSUE TITLE
Clearer output

### ISSUE THREAD

**Issue by Chr1stian** [entur/terraform-google-memorystore#10]
Could you make it clearer in the README what the output will be? E.g the name of the configmap to be used in Helm configs

**Comment by AlexanderBrevig** [comment]
You are more than welcome to give it a shot :) I think we all agree that the docs could be better. Please name the PR with prefix `docs:` i.e `docs: add instance and config map names to README`.

The reason it's not already in the docs is that [terraform-docs](https://github.com/terraform-docs/terraform-docs) has no way of automatically adding such documentation AFAICT.

If you want to have a go, please add the custom doc above `<!-- BEGIN_TF_DOCS -->` or below `<!-- END_TF_DOCS -->` as anything between hose will be replaced by the documentation tool. 

There's also the problem of it becoming out of date, but I guess that's what we have issues and PRs for :) Maintaining such things.
