### ISSUE TITLE
Read replica support

### ISSUE THREAD

**Issue by assadriaz** [entur/terraform-google-memorystore#7]
Current release of this module doesn't support read replicas of redis, we have an application [lamassu](https://github.com/entur/lamassu-deployment-config/blob/master/terraform/main.tf), that uses read replicas. Can you add this feature in this module

`var1 read_replicas_mode 
var2 no-of-replicas`

This changes also requires changes in **main_redis_connection**
e.g.
`data = {
    REDIS_HOST = google_redis_instance.main.host
    REDIS_PORT = google_redis_instance.main.port
    REDIS_READ_HOST = google_redis_instance.main.read_endpoint
    REDIS_READ_PORT = google_redis_instance.main.read_endpoint_port
  }`

**Comment by testower** [comment]
I think it also needs to support replica_count argument

**Comment by EnturWilhelm** [comment]
Implemented in https://github.com/entur/terraform-google-memorystore/releases/tag/v0.2.0
